#!/bin/bash

echo "Writing .env file for docker-compose"
cat > .env <<EOF
# Variables for docker-compose
# *Do not edit this file*, it is
# written when running "sh configure.sh"
_UID=$(id --user)
_GID=$(id --group)
EOF
